config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'
  root to: "pages#index"
  
  resources :activities
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :activity_type
    delegate :name, to: :activity_type
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :activities, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = current_user.activities
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)
    @activity.user = current_user
    respond_to do |format|
      if @activity.save
        format.html { redirect_to activities_url, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activities_url, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :date, :duration, :activity_type_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
  <div class="field">
    <%= form.label :name %><br />
    <%= form.collection_select(:activity_type_id, ActivityType.all, :id, :name, {:prompt => 'Select an Acitvity'}, id: "activity_name" ) %>
</div>
<div class="field">
    <%= form.label :date %><br />
    <%= form.date_field :date, id: "activity_date"%>
</div>
<div class="field">
    <%= form.label :duration %><br />
    <%= form.number_field :duration, id: "activity_duration"%>
</div>
    <%= form.submit :class => "submit-button" %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<div class="jumbotron new_activity">
<div class="vertical-align">
<h2>Editing Activity</h2>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>
</div>
</div>

app/views/activities/index.html.erb
<div class="jumbotron">
  <h3>Activities</h3>
  <div class="row">

    <% @activities.each do |activity| %>
      <div class="activity col-lg-3 col-md-4 col-sm-6">
        <div style="background-image: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.5)), url('assets/<%= activity.activity_type.image %>');" class="image">
          <h5><%= activity.name %></h5>
          <p><i class="far fa-calendar"></i> <%= activity.date.strftime("%d - %m - %Y") %></p>
          <p><i class="far fa-clock"></i> <%= activity.duration %> mins</p>
        </div>
        <div class="modify">
          <%= link_to '<i class="fas fa-trash"> </i>'.html_safe, activity, method: :delete, data: { confirm: 'Are you sure?' },  :class => "float-right" %>
          <%= link_to 'Edit', edit_activity_path(activity),  :class => "float-right" %>
          </div>
      </div>
    <% end %>

  </div>
  <br>

  <%= link_to 'New Activity', new_activity_path, :class => "submit-button" %>
</div>

app/views/activities/new.html.erb
<div class="jumbotron new_activity">
    <div class="vertical-align devise">
        <h2>New Activity</h2>
        
        <%= render 'form', activity: @activity %>
        
        <%= link_to 'Back', activities_path %>
    </div>
</div>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Move & Groove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/"><%= image_tag("favicon.png", :width => 30) %> Move & Groove</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-right" id="navbarText">
      <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item active">
          <a class="nav-link" href="/activities">Activities</a>
        </li>
        <li class="nav-item active">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-outline-secondary" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, :class => "btn btn-outline-secondary" %>
        </li>
      <% end %>
      </ul>
    </div>
  </nav>

  <body>
    <%= yield %>
  </body>

  <!-- Footer -->
  <footer class="page-footer font-small indigo">
  
      <!-- Footer Links -->
      <div class="container">
  
        <!-- Grid row-->
        <div class="row text-center d-flex justify-content-center pt-5 mb-3">
  
          <!-- Grid column -->
          <div class="col-md-2 mb-3">
            <h6 class="text-uppercase font-weight-bold">
              <a href="/">About</a>
            </h6>
          </div>
          <!-- Grid column -->

          <% if current_user %>
          <!-- Grid column -->
            <div class="col-md-2 mb-3">
              <h6 class="text-uppercase font-weight-bold">
                <a href="/activities">Activities</a>
              </h6>
            </div>
            <!-- Grid column -->

            <div class="col-md-2 mb-3">
              <h6 class="text-uppercase font-weight-bold">
                <%= link_to "Logout", destroy_user_session_path, method: :delete %>
              </h6>
            </div>
            <!-- Grid column -->

          <% else %>
            <!-- Grid column -->
            <div class="col-md-2 mb-3">
              <h6 class="text-uppercase font-weight-bold">
              <%= link_to "Sign Up", new_user_registration_path %>
              </h6>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-2 mb-3">
              <h6 class="text-uppercase font-weight-bold">
                <%= link_to "Login", new_user_session_path %>
              </h6>
            </div>
            <!-- Grid column -->
          <% end %>

        </div>
        <!-- Grid row-->
        <hr class="rgba-white-light" style="margin: 0 15%;">
  
        <!-- Grid row-->
        <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">
  
          <!-- Grid column -->
          <div class="mb-5 col-md-8 col-12 mt-5">
            <p style="line-height: 1.7rem">Move & Groove allows you to track your fitness progress by keeping record of your fitness acitivities. 
            This sublime interface will give you the motivation you need to improve your everyday physical health. </br>Join the Move & Groove community today!</p>
          </div>
          <!-- Grid column -->
  
        </div>
        <!-- Grid row-->
        <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">
  
        <!-- Grid row-->
        <div class="row pb-3">
  
          <!-- Grid column -->
          <div class="col-md-12">
  
            <div class="mb-5 text-center">
                <a class="fab fa-facebook-f fa-lg mr-4 " href="#"> </a>
                <a class="fab fa-twitter fa-lg mr-4" href="#"> </a>
                <a class="fab fa-google-plus-g fa-lg mr-4" href="#"> </a>
                <a class="fab fa-linkedin-in fa-lg mr-4" href="#"> </a>
                <a class="fab fa-instagram fa-lg mr-4" href="#"> </a>
                <a class="fab fa-pinterest fa-lg" href="#"> </a>
            </div>
  
          </div>
          <!-- Grid column -->
  
        </div>
        <!-- Grid row-->
  
      </div>
      <!-- Footer Links -->
  
      <!-- Copyright -->
      <div class="footer-copyright text-center py-3">© 2019 Copyright:
        <a href="/"> Move&Groove.com</a>
      </div>
      <!-- Copyright -->
  
    </footer>
    <!-- Footer -->
  
</html>

app/views/pages/index.html.erb
<div class="jumbotron container-full-bg-index">
    <div class="text-right center">
        <h1><span class="bg-white"><strong>Move & Groove</strong></span></h1>
        <h2><span class="bg-white">Fitness starts with you.</span></h2>
        <p><span class="bg-white">Move & Groove is a free website that helps you track your fitness.</span></p>
    </div>
</div>